name: CI/CD

on:
  push:

jobs:
  test_return:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Integration test: return'
        id: output-set
        uses: ./
        with:
          script: |
            "return"
      - run: |
          expected="return"
          output="${{steps.output-set.outputs.result}}"
          [[ "$output" != "$expected" ]] && echo "::error::❌ Expected '$expected', got '$output'" && exit 1
          echo "✅ Test passed, outputs.result: ${{toJSON(steps.output-set.outputs.result)}}"
